version: '2'
services:
    dev:
        image: python:2.7
        volumes:
            - ./oulipo/frontend:/html
        working_dir: /html
        command: "python -m SimpleHTTPServer 8888"    
        ports:
            - "8888:8888"
        depends_on:
            - api
    api:
        build: .
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - celery
    celery:
        build: .
        image: celery:3.1
        command: "celery -A oulipo worker --loglevel=info"
        links:
            - rabbitmq:rabbitmq
    rabbitmq:
        image: rabbitmq:3.6
