version: '2'
    
services:
    dev:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile_server
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - worker
        volumes:
            - ./oulipo:/oulipo
            - ./logs:/logs
        ports:
            - "80:80"
            - "8000:8000"
        environment:
            DEVELOPMENT: "true"

    prod:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile_server
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - worker
        volumes:
            - ./logs:/logs
        ports:
            - "80:80"
            - "8000:8000"

    tests:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile_worker
        volumes:
            - ./oulipo:/oulipo
        command: python manage.py test

    worker:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile_worker
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - rabbitmq
        volumes:
            - ./oulipo:/oulipo

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3
