# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='id',
        ),
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
