# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20161212_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='created_at',
        ),
    ]
