FROM python:2.7
MAINTAINER Sam Whitehall <me@samwhitehall.com>

ENV INSTALL_PATH /oulipo

RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH


# Install requirements & spaCy english corpus
COPY requirements requirements
RUN pip install -r requirements
RUN python -m spacy.en.download

# Don't run as root
RUN useradd -ms /bin/bash oulipo
USER oulipo


CMD celery -A oulipo worker --loglevel=info
